title: Test title
theme: jekyll-theme-cayman

# Defaults
defaults:
  
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"
